# Use the official MySQL image
FROM mysql:latest

# Copy SQL initialization script
COPY ./db /docker-entrypoint-initdb.d
COPY ./init.sql /docker-entrypoint-initdb.d/init.sql

# Set environment variables
ENV MYSQL_DATABASE lamp_docker
ENV MYSQL_USER lamp_docker
ENV MYSQL_PASSWORD PixelDoctor123!

ENV MYSQL_ROOT_PASSWORD password
ENV MYSQL_ALLOW_EMPTY_PASSWORD 1

ENV MYSQL_DATA_DIR /var/lib/mysql
ENV MYSQL_INITDB_SKIP_TZINFO 1

EXPOSE 3306

# Use the entrypoint script provided by the official MySQL image
ENTRYPOINT ["docker-entrypoint.sh"]

# Start MySQL server
CMD ["mysqld", "--console", "--init-file=/docker-entrypoint-initdb.d/init.sql"]

