# Use the official phpMyAdmin image
FROM phpmyadmin/phpmyadmin

# Set environment variables
ENV PMA_HOST=db
ENV PMA_PORT=8080

# Expose port 8080
EXPOSE 8080

# Start phpMyAdmin server
CMD apache2-foreground -DFOREGROUND -e info -D MPM=event
